### ISSUE TITLE
Add Readiness Probe at deployment time

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#102]
Currently, if someone wants a readiness probe added to there application, they could install kube-probe

But would it be possible for nodeshift to add this functionality at "build time" so a user wouldn't worry about installing kube-probe then setting it up, and then adding that to there deployment config

What is the most unobtrusive way we could do this.

Possibly way could be we have a wrapper that spawns another process?

**Comment by helio-frota** [comment]
when using jest, we don't need to require('jest')
I have no idea how the magic woks, here an example:
https://github.com/helio-frota/listjs/blob/master/test/listjs.test.js

I only did:

1. npm install jest -D
2. https://github.com/helio-frota/listjs/blob/master/package.json#L17

btw, I'm not sure if this kind of magic applies to kube-probe

**Comment by lholmquist** [comment]
I'm thinking now that we don't worry about trying to inject kube-probe into the code, but instead look to see if kube-probe has been added and then if so, "enrich" the deployment config with the default endpoints.

If the user does use kube-probe but uses different endpoints, then the user would need to supply those endpoints in the deploymentConfig. and the default one would just get merged
