### ISSUE TITLE
Resource file string substitution

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#13]
For a resource like this svc.yml:

    apiVersion: v1
    kind: Service
    metadata:
      name: ${project.name}
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      type: ClusterIP

we need to be able to replace that ${project.name} with the name of the user project

**Comment by lholmquist** [comment]
It looks like the code will use the correct project name, https://github.com/bucharest-gold/nodeshift/blob/master/lib/services.js#L20  overwriting what is in that yaml.  maybe that should also be different?  or maybe the user doesn't need to specificy that metadata section since nodeshift will just add it anyway

**Comment by lholmquist** [comment]
Another use case here is the ability to also pass in values(from the command line or the API) that will  replace a value.

For instance, in the SSO booster, the SSO_URL is passed into the maven plugin during the deploy phase.  

We should probably have something on the cli where you can specify one or more values to substitute.  
something like:
`nodeshift -e SSO_URL=thing -e OTHER_SUB=other thing`

or something similar,  not sure about the `-e`

then of course, there would be a similar thing passed into the options for the API

**Comment by lance** [comment]
@lholmquist I'm not crazy about the `-e` flag. What about just using the environment, and only look for env vars that are prefixed? For example something like this

```
$ NODESHIFT_SSO_URL=https://whatever:8443/auth ./nodeshift [args]
```

**Comment by lholmquist** [comment]
i actually switched it to `-d`  but i'm guessing it's not really the letter that matters :)

i originally thought about doing that way,  but i think the reason i went with `nodeshift -d KEY=VALUE` was docker(and maven) was doing it that way.  and it seemed to read a little nicer.  like i could clearly see that i was running the nodeshift command.

and yargs has a nice Array thing https://github.com/yargs/yargs/blob/master/docs/tricks.md#arrays

but i am not set in stone here

**Comment by lance** [comment]
OK - that all makes sense and works for me. 👍
