### ISSUE TITLE
Build Logs not streaming to the console

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#143]
The build logs are not streaming to the console anymore. instead the whole logs will output to the console once it is totally finished building on the server.

I think it might be because of our async/await usage in that part of the code(?)

**Comment by lance** [comment]
Do you mean the `TRACE` lines?

**Comment by lholmquist** [comment]
right,  the TRACE lines,  whats coming from the server

**Comment by lance** [comment]
It appears that this is possibly a result of changes to minishift and how the API responds. Previously, the API responded asynchronously, but now the HTTP connection persists until the build has completed.
