### ISSUE TITLE
Do we need to generate a Dockerfile?

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#15]
The maven plugin generates a docker file that is included with the src code.  The generated dockerfile is responsible for copying the code to the correct place.

In the nodeshift plugin, i'm specifying in the build-config to use the s2i docker image, which does all that copying for us,  the generated dockerfile is not used(i think,  its currently in the wrong place too).

perhaps i can leave that part out for now

**Comment by lance** [comment]
If we don't need it, and it's not being used, I'd say then we don't need to bother generating one.

**Comment by lholmquist** [comment]
I'm going to re-open this until we figure out exactly why the maven plugin is creating one,

This is the s2i-java image that the maven plugin uses,

https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/s2i/assemble#L166

That line does something interesting,  not totally sure whats going on

**Comment by lholmquist** [comment]
Just asked the question on Fabric8;s irc/slack

**Comment by lholmquist** [comment]
Here is the reply:

"It can be used yeah; there is pure docker building (eg on kubernetes or when you have access to the Docker socket), pure s2i then the s2i binary build option which is a hybrid where you make your artefact locally (eg jar/war) and copy it in"

I think for what we are doing now though,  we can probably remove it.
