### ISSUE TITLE
doc: .nodeshift directory and yml files are not created

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodeshift#158]
from the docs:

>The .nodeshift directory contains your resource fragements. These are .yml files that describe your services, deployments, routes, etc. By default, nodeshift will create a Service and DeploymentConfig if none are provided.

steps to reproduce:
1. `npm install nodeshift -D`
2. Add required `scripts` and `files` section on package.json
```
"scripts": {
  "openshift": "nodeshift --osc.strictSSL=false"
}
```
3. run `npm run openshift`

**Comment by lholmquist** [comment]
i think this is a README issue.  nodeshift creates the missing files "in-memory", it doesn't actually create "real files" if ones are missing

**Comment by helio-frota** [comment]
make sense :+1: title updated.
