### ISSUE TITLE
unbuild command?

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#190]
Currently we have undeploy,  this removes the application specific stuff that gets created during the apply-resource goal.

We don't have anything currently exposed that will remove the buildConfig, builds and Imagestreams that we create during the build phase.

there is the `build.recreate` option that a user can pass in to remove builds/imagestreams, but a build is run after that.

This would be more a method for our integration test framework, [rhoaster](https://github.com/bucharest-gold/rhoaster).  The code is there to delete these things, but it is inside of the build and imagstream files.  We would need to break that out into its own thing perhaps.

I don't really like the name "unbuild" so i'm open to suggestions.

**Comment by helio-frota** [comment]
* removeBuild
* deleteBuild
* undoBuild :-1: 
* destroy
* erase
* undo

**Comment by lance** [comment]
Would it be useful maybe to have `undeploy` accept a flag that tells it to remove everything?

**Comment by lholmquist** [comment]
i think having that flag for undeploy might be how i go.  i'll try that out first and see how it feels
