### ISSUE TITLE
Remove message about node version choice

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#194]
Currently if the `--nodeVersion` flag is used with a version that is not in our hard-coded list https://github.com/bucharest-gold/nodeshift/blob/master/bin/nodeshift#L29,
 then we emit a warning.

We started talking about have more point releases as well as `cr` releases, i'm tempted to take this check out

@lance @helio-frota any thoughts

**Comment by lance** [comment]
Easy thing is to remove the check. More fancy and of questionable benefit is to simply check major version number through a regex.

**Comment by helio-frota** [comment]
@lholmquist I agree with @lance

**Comment by lholmquist** [comment]
probably just going to remove the check

**Comment by lance** [comment]
@lholmquist Makes sense - we just need to have a user-friendly failure mode when the node version specified is not available

**Comment by lholmquist** [comment]
hmmmm.  i'll have to think about that one.  the error will happen during the build on openshift,  so i might need to parse the error message that is returned.  i'll play with it
