### ISSUE TITLE
Unable to use nodeshift in Katacoda environments

### ISSUE THREAD

**Issue by jamesfalkner** [bucharest-gold/nodeshift#197]
I went to upgrade to latest nodeshift in a [project that runs in a Katacoda environment](https://learn.openshift.com/middleware/rhoar-getting-started-nodejs), where the configuration file for the oc command is *not* at `~/.kube/config`. It's actually at `/openshift.local.config/master/admin.kubeconfig`, and I was using the configLocation in nodeshift to point at it. I'm not an expert at kubernetes config locations and don't know if this is a bad practice, but removing this from nodeshift prevents my project from using latest nodeshift as this environment does not place the kube config file in the place that nodeshift now requires.

**Comment by jamesfalkner** [comment]
Wahoo!! Once this shows up in a npm-consumable release I'll be sure to remove my workarounds (which right now is a symlink added to `~/.kube` :) )

**Comment by lholmquist** [comment]
@jamesfalkner i just published it to npm,  as 1.5.0
