### ISSUE TITLE
nodeshift potentially hangs and grows archive file indefinitely

### ISSUE THREAD

**Issue by rhoads-zach** [bucharest-gold/nodeshift#200]
If you don't specify `files` in package.json (e.g. https://github.com/bucharest-gold/nodejs-rest-http/blob/master/package.json#L30), app could hang and grow indefinitely when running `npm run openshift`.

Example project:
https://github.com/rhoads-zach/swagger-app

to reproduce:
```
git clone https://github.com/rhoads-zach/swagger-app.git
cd swagger-app
npm install && npm run openshift
```

After 1 minute check `tmp/nodeshift/build/archive.tar` and notice it is several GB and growing.

**Comment by helio-frota** [comment]
@rhoads-zach hi, 

Maybe this is something related to the missing `files` section on `package.json`.

please try to add the `files` section example:
https://github.com/bucharest-gold/mean-booster/blob/master/package.json#L19-L24

**Comment by rhoads-zach** [comment]
thanks @helio-frota that does resolve the issue, but i believe @lholmquist is looking into why this is happening in general

**Comment by lholmquist** [comment]
@helio-frota yea,  that would help.  

i noticed something intersting, if i don't have a node_modules folder, the archive happens fine.  but with the node_modules folder things get crazy


Probably will have to ignore that directory when archiving with out the files prop

**Comment by rhoads-zach** [comment]
FYI, i applied the `files` fix to my repo. in case you still need the old verison to reproduce, its here:
https://github.com/rhoads-zach/swagger-app/tree/50af94cbdcc6a7f08c254c300738b28fa7628554
