### ISSUE TITLE
DeploymentConfig - Add a default PORT=8080 environment variable

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#214]
During the creation of the deployment config, should we inject an environment variable related to the PORT.

In our boosters, we have some thing like this:

```
const port = process.env.PORT || '3000';
```
And the liveness and readiness probes that nodeshift will create for the user, will use port 8080

usually, it is enough to set the port value in the npm start script, but related to this issue: https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/33 nodemon seems to not pay attention to env vars in the start script.

do we help the user out by just adding an environemnt variable into the deploymentConfig

**Comment by lance** [comment]
I think maybe - but we should respect (and document how to set) a PORT value in your deployment.yaml.

**Comment by lholmquist** [comment]
yea,  of course.  and i think this issue also goes along with #216 about not hardcoding port 8080

**Comment by lholmquist** [comment]
The more i think about this, the more i'm not sure if this is a great addition.   I might just be adding this for my own purpose, which is being able to deploy a express app in 2 steps instead of 3.  But is this really valuable? 

Does it add to much magic to nodeshift?  At the moment, you can only override the value, not remove it completely.

Also, if someone adds this to there start script `PORT=3000 node .`, then the PORT value will be 3000 inside the pod, but the environment variable will still be 8080 if you were to look in the Openshift UI, which can get confusing.

The PR is ready for this,  but maybe we should hold off.

I guess one of the reasons for adding this was for the nodemon debug issue, https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/33#issuecomment-382587104 

It might be better just to say,  "this is how you add an env variable to your deployment config in the .nodeshift directory" instead


@lance thoughts on that ramble

**Comment by lance** [comment]
> Also, if someone adds this to there start script PORT=3000 node ., then the PORT value will be 3000 inside the pod, but the environment variable will still be 8080 if you were to look in the Openshift UI, which can get confusing.

This is the tricky part that makes me tend to agree with your assessment here. Perhaps we should just let sleeping dogs lie.

**Comment by lholmquist** [comment]
Thanks.

I'm going to close this with a won't fix label,  and we can revisit if we need to
