### ISSUE TITLE
Check that the deployment has finished

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#31]
We need to check the the deployment has finished.

After all the resource files have been applied, we just resolve our Promise,  we also need to ping the service endpoint(?) and check its status

**Comment by lholmquist** [comment]
I noticed that the maven plugin, doesn't do this,  it just gives this hint: 'F8: HINT: Use the command `oc get pods -w` to watch your pods start up"

**Comment by lholmquist** [comment]
Possibly look into the liveness/readiness probes?  Not all apps might have these endpoints defined, so i don't think we can rely on this.  

It's possible that adding this doesn't make sense since node apps seem to come up really quickly and we probably don't want to block nodeshift from completing if a liveness endpoint wasn't defined.

I think were we probably need something like this is in the yet to be created, much talked about :),  testing framework

**Comment by lholmquist** [comment]
There is an endpoint for pods:  https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#read-the-specified-pod

There is also a status field on the returned object, i've seen "Running" and "Pending",  this endpoint assumes you have the pod name, which i'm totally sure how to get. we could use a labelSelector, like "deployment" which should only return just the pod we want.

I wonder if Nodeshift should return an object with some of this info after it completes?

**Comment by helio-frota** [comment]
> I wonder if Nodeshift should return an object with some of this info after it completes?

Would be nice to have something to check (for example) the kube-probe liveness endpoint.
Then we can use travis + `oc cluster up` and check if the app is deployed and running.

:+1:

**Comment by helio-frota** [comment]
I'm using `curl` here https://travis-ci.org/bucharest-gold/mean-booster/jobs/315046339#L1466
so would be good to have something on nodeshift to avoid an extra - external (curl) - step to check if the app was deployed and running.

**Comment by lance** [comment]
Rhoaster deals with this. Closing for now.
