### ISSUE TITLE
Make s2i base image configurable

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#38]
Currently the s2i image we use is hardcoded to use the latest from "bucharestgold/centos7-s2i-nodejs:latest"

This should be configurable

**Comment by lance** [comment]
Do you think this should be configuration of the tag only, and the base image - `bucharestgold/centos7-s2i-nodejs` is constant? Seems reasonable for now...

**Comment by lholmquist** [comment]
I think that makes sense.

Perhaps we revisit when this isn't so openshift specific

**Comment by lance** [comment]
Connects to #45
