### ISSUE TITLE
Deploy multiple projects

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#84]
A feature that the maven plugin has, is to be able to deploy multiple projects at once.

Our circuit breaker booster is a good example.  https://github.com/bucharest-gold/nodejs-circuit-breaker

not sure how it would work,  but it would be nice

**Comment by lance** [comment]
I created a branch to start working on this, but ended up not writing any code. It could be purely a lack of imagination on my part, but I don't really see a good way to do this without overly complicating the code. Think about the use cases.

What if you only want apply resources to one project, but deploy the other project? Or some such thing. In any case, to me, it seems that the current way things work is nice and clean and by adding the ability to handle multiple projects, we'll be adding many many more possible use cases. To me the flexibility required for something like this to be truly useful is perhaps best handled by allowing the user to orchestrate it however they want, e.g. https://github.com/bucharest-gold/nodejs-circuit-breaker/blob/master/start-openshift.sh.

Just my two cents - counter arguments welcome.

**Comment by lholmquist** [comment]
I agree with you here.  No need to make the code more complicated if it can be easily done with a shell script.

I think it would have needed an outer package.json that somehow referenced the inner two projects package.json. That just sounds messy even typing it.  And that doesn't seem very node-y.  we aren't maven :)

going to close this then
