### ISSUE TITLE
The output is showing wrong timezone value

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodeshift#93]
```console
2017-10-13T14:05:53.663Z INFO loading configuration
2017-10-13T14:05:53.684Z INFO using namespace mb at https://192.168.42.44:8443
2017-10-13T14:05:53.690Z INFO creating archive of ./
```
`14:05:53` but now here is `11:13`

**Comment by lholmquist** [comment]
This is the code `new Date()).toISOString()`  samething happens here

**Comment by helio-frota** [comment]
here is undefined

```console
[hf@localhost ~]$ node
> process.env.TZ
undefined
```

**Comment by lance** [comment]
I think this is behaving as expected. Unless you have [`$TZ`](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html) set in your environment. In that case, I think it should print whatever time zone you have. The default is `GMT`.

**Comment by helio-frota** [comment]
weird, I didn't set anything.
And the log shows 3 hours ahead.

**Comment by lholmquist** [comment]
"And the log shows 3 hours ahead."  i think thats correct, since it is showing 5 hours ahead for me,  and we are 2 hours apart

**Comment by helio-frota** [comment]
@lance @lholmquist 
I got it : ]
I remember issues like this one from "Java world".
Since my laptop is not a server I have no concerns to set the timezone, for example to save records into a database or something.
