### ISSUE TITLE
Add 'http://' to the url output, then is possible to click and open the default browser

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodeshift#95]
details:

```console
2017-10-13T16:06:02.880Z INFO route host mapping mean-booster-mb.192.168.42.44.nip.io
```
`http://` added
```console
2017-10-13T16:06:02.880Z INFO route host mapping http://mean-booster-mb.192.168.42.44.nip.io
```

**Comment by lholmquist** [comment]
it is also possible that it could be `https` 

https://github.com/bucharest-gold/nodeshift/blob/master/lib/routes.js#L45 that is where it is happening.   i wonder if there is more info from that route object that is returned?

**Comment by helio-frota** [comment]
Agree.

@lholmquist on this step, nodeshift returns this:

```
2018-02-19T13:30:01.721Z INFO using namespace myproject at https://127.0.0.1:8443
```
`https`

I really don't know if the same can be done with the route.

**Comment by lholmquist** [comment]
we now return a whole object of stuff when nodeshift finishes,  and rhoaster does something to figure out the url of the route.  so we might already have something for this

**Comment by lholmquist** [comment]
@helio-frota can i close?

**Comment by helio-frota** [comment]
yes
