### ISSUE TITLE
Better error message if not logged in

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/nodeshift#98]
related to #97, it seems the UX is a bit bad when you are not logged in, or don't have the correct permissions to perform an operation.

**Comment by lance** [comment]
Waiting for integration of https://github.com/bucharest-gold/openshift-rest-client/commit/f0d9f06d73cc22fcf6115e0d750c0566e47ceaf9 into a release of `openshift-rest-client`.

**Comment by lholmquist** [comment]
updated openshift-rest-client  https://github.com/bucharest-gold/nodeshift/pull/135 with changes from https://github.com/bucharest-gold/openshift-rest-client/pull/47
